export const Images = {
    LOGO_Image: require('../Assets/Images/Logo/logo.png'),
    BackBuuton: require('../Assets/Images/Backbutton/backbutton.png'),
    Splash_logo: require('../Assets/Images/SplashLogo/splashLogo.png'),
    WELCOME_1: require('../Assets/Images/Welcome1/welcome.png'),
    WELCOME_2: require('../Assets/Images/welcome2/welcome2.png'),
    WELCOME_3: require('../Assets/Images/Welcome3/welcome3.png'),
    SALOON_TYPES: require('../Assets/Images/Saloontype/saloontype.png'),
    SALOON_TYPE: require('../Assets/Images/Seasor/seasor.png'),
    USER_TYPE: require('../Assets/Images/TypeUser/user.png'),
    BottomHome: require('../Assets/Images/home/home.png'),
    BottomScissor: require('../Assets/Images/bottomseasor/bottomseasor.png'),
    BottomUsers: require('../Assets/Images/bottomUsers/bottomUsers.png'),
    BottomUserIcon: require('../Assets/Images/bottomUserIcon/bottomUserIcon.png'),
    kycForm: require('../Assets/Images/kycform/kycform.png'),
    Notification: require('../Assets/Images/notification/notification.png'),
    NotificationUser: require('../Assets/Images/notificationUser/notificationUser.png'),
    SIGN_IN_LOCATION: require("../Assets/Images/SignupLocation/Group33300.png"),
    HOME_BANNER:require("../Assets/Images/bannerImage/bannerImage.png"),
    SEARCH_ICON:require("../Assets/Images/searchIcon/searchIcon.png"),
    CHOTI_DESIGN:require('../Assets/Images/chotiDesign/chotiDesign.png'),
    BOTTOM_CART:require('../Assets/Images/BottomCart/BottomCart.png'),
    BOTTOM_BOOKING:require('../Assets/Images/BottomBooking/BottomBooking.png'),
    LOCATION:require('../Assets/Images/Location/Location.png'),
    HAIRCUTTINGS:require('../Assets/Images/haircutting/haircutting.png'),
    LOCATION_DETECT:require('../Assets/Images/locationDetect/locationDetect.png'),
    CROSS_ICONS:require('../Assets/Images/crossIcon/crossIcon.png'),
    USERS_ADS:require('../Assets/Images/userAds/userAds.png'),
    SALLON_BG_IMAGE:require('../Assets/Images/sallonbgImage/sallonbgImage.png'),
    UNLIKE:require('../Assets/Images/unlike/unlike.png'),
    STAR:require('../Assets/Images/star/star.png'),
    EDIT:require('../Assets/Images/edit/edit.png'),
    LOGIN_USER_IMAGE:require('../Assets/Images/personImage/personImage.png'),
    CONTACTUSIMAGE:require('../Assets/Images/contactUs/contactUs.png'),
    Mobile_phone:require('../Assets/Images/mobilePhone/mobilePhone.png'),
    Whatsapp:require('../Assets/Images/whatsapp/whatsapp.png'),
    Instagram:require('../Assets/Images/instagrma/instagrma.png'),
    Facebook:require('../Assets/Images/facebook/facebook.png'),
    Twitter:require('../Assets/Images/twitter/twitter.png'),
    Profit:require('../Assets/Images/profit/profit.png'),
    EMAIL:require('../Assets/Images/mail/mail.png'),
    UniIcon:require('../Assets/Images/uniIcon/uniIcon.png'),
    BookingUserIcon:require('../Assets/Images/bookingUserIcon/bookingUserIcon.png'),
    AC:require('../Assets/Images/ac/ac.png'),
    TV:require('../Assets/Images/tv/tv.png'),
    Sofa:require('../Assets/Images/sofa/sofa.png'),
    Newspaper:require('../Assets/Images/newspaper/newspaper.png'),
    Magzine:require('../Assets/Images/magzine/magzine.png'),
    SaloonUser:require('../Assets/Images/saloonUser/saloonUser.png'),
    SaloonBgGallery:require('../Assets/Images/saloonBgGallery/saloonBgGallery.png'),
    BGBack:require('../Assets/Images/bgBack/bgBack.png'),
    NoInternet:require('../Assets/Images/Nointernet/Nointernet.png'),
}