export const Images = {
    LOGO_Image: require('../Assets/Images/Logo/logo.png'),
    BackBuuton: require('../Assets/Images/Backbutton/backbutton.png'),
    Splash_logo: require('../Assets/Images/SplashLogo/splashLogo.png'),
    WELCOME_1: require('../Assets/Images/Welcome1/welcome.png'),
    WELCOME_2: require('../Assets/Images/welcome2/welcome2.png'),
    WELCOME_3: require('../Assets/Images/Welcome3/welcome3.png'),
    SALOON_TYPES: require('../Assets/Images/Saloontype/saloontype.png'),
    SALOON_TYPE: require('../Assets/Images/Seasor/seasor.png'),
    USER_TYPE: require('../Assets/Images/TypeUser/user.png'),
    BottomHome: require('../Assets/Images/bottomHome/bottomHome.png'),
    BottomScissor: require('../Assets/Images/bottomseasor/bottomseasor.png'),
    BottomUsers: require('../Assets/Images/bottomUsers/bottomUsers.png'),
    BottomUserIcon: require('../Assets/Images/bottomUserIcon/bottomUserIcon.png'),
    kycForm: require('../Assets/Images/kycform/kycform.png'),
    Notification: require('../Assets/Images/notification/notification.png'),
    NotificationUser: require('../Assets/Images/notificationUser/notificationUser.png'),
    SIGN_IN_LOCATION: require("../Assets/Images/SignupLocation/Group33300.png"),
    HOME_BANNER:require("../Assets/Images/bannerImage/bannerImage.png"),
    SEARCH_ICON:require("../Assets/Images/searchIcon/searchIcon.png"),
    CHOTI_DESIGN:require('../Assets/Images/chotiDesign/chotiDesign.png'),
}