export const Routes = {
    Splash: 'Splash',
    Signin: 'Signin',
    Signup: 'Signup',
    Welcome: 'Welcome',
    CreatePin: 'CreatePin',
    ChooseType: 'ChooseType',
    Barber: 'Barber',
    User: 'user',
    BarberHome: 'Home',
    BarberOrders: 'Orders',
    BarberSaloon: 'My Salons',
    BarberProfile: 'Profile',
    TrendingList: 'TrendingList',
    TrendingDetails: 'TrendingDetails',
    UserHome: 'Home',
    UserSearch: 'Search',
    UserBookings: 'Booking',
    UserCart: 'Cart',
    UserProfile: 'Profile',
    ContactUs: 'contactus',
    AppVersion: 'appversion',
    FeedBack: 'feedback',
    Review: 'review',
    PrivacyPolicy: 'privacypolicy',
    UserBooking: 'userBooking',
    UserFavouriteSaloon: 'userfavouritesaloon',
    ReferEarn: 'referEarn',
    UserBookingSaloon: 'userbookingsaloon',
    UserSaloonDetails: 'userSaloonDetails',
    UserReviewList: 'UserReviewList',
    UserRecommendedBarber: 'UserRecommendedBarber',
    SaloonBookingScreen: 'SaloonBookingScreen',
    UserServices: 'UserServices',
    SaloonGallery: 'SaloonGallery',
    UserLocationMap: "UserLocationMap"

}