export const TextConstant={
    SplashText:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    WELCOME_1_DESC:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    WELCOME_2_DESC:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    WELCOME_3_DESC:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    FOR_SALOON:'For Salon',
    FOR_USER:'For User',
    //Sign In Texts
    SignIn_heading:"Sign in",
    SignIn_subHeading:"Welcome! Please enter your details",
    SignIn_label_one:"Mobile Number",
    SignIn_placeholder_one:"Mobile Number",
    SignIn_label_two:"Enter MPIN",
    SignIn_placeholder_two:"Enter MPIN",
    signIn_bottomInfoText_left_one:"Are you a New User?",
    signIn_bottomInfoText_left_two:"Please Sign up!",
    signIn_bottomInfoText_right:"Forgot MPIN?",
    //Sign Up Texts
    SignUp_heading:"Sign Up",
    SignUp_subHeading:"Greeting From DiZi Salon!",
    SignUp_label_one:"Salon Owner Name*",
    SignUp_placeholder_one:"e.g., John Doe",
    SignUp_label_two:"Salon Name*",
    SignUp_placeholder_two:"e.g., DiZi Salon",
    signUp_label_three:"Phone Number*",
    signUp_label_five:"E-Mail Address*",
    create_pin_heading:"Create MPIN",
    create_pin_subheading:"Greeting From DiZi Salon!",
    create_pin_label_one:"New MPIN",
    create_pin_label_two:"Confirm MPIN",
    Phone_number:'Phone Number*',
    OTP_NUMBER:'OTP',
    KYC_MAIN_TEXT:'Let’s do KYC and List your Salon',
    KNOW_MORE:'Know More',
    LIST_NOW:'List Now',
    TRENDING_STYLE:'Trending Style’s',
    SHOW_MORE:'Show More',
    SEARCH_TEXT:'Search for Styles',
    CHOTI_Title:'Chotli Braid',
    LOCATION:'Location',
    CATEGORIES:'Categories'


}